function agent_run_simulation(config_path, result_path)
%AGENT_RUN_SIMULATION Execute JSON -> MATLAB focus simulation -> JSON.

started = tic;
task_id = "";
try
    validateattributes(config_path, {'char', 'string'}, {'scalartext'});
    validateattributes(result_path, {'char', 'string'}, {'scalartext'});
    config_path = string(config_path);
    result_path = string(result_path);
    if ~isfile(config_path)
        error('hermes:ConfigNotFound', ...
            'Configuration file does not exist: %s', config_path);
    end

    try
        config = jsondecode(fileread(config_path));
    catch exception
        error('hermes:JsonParseError', ...
            'Could not parse configuration JSON: %s', exception.message);
    end
    if ~isstruct(config) || ~isscalar(config)
        error('hermes:InvalidConfig', ...
            'Configuration JSON must decode to one object.');
    end
    if isfield(config, 'task_id')
        if ~(ischar(config.task_id) || ...
                (isstring(config.task_id) && isscalar(config.task_id)))
            error('hermes:InvalidTaskId', 'task_id must be a scalar string.');
        end
        task_id = string(config.task_id);
    else
        error('hermes:MissingTaskId', 'Required field task_id is missing.');
    end
    if ~isfield(config, 'target_mm')
        error('hermes:MissingTarget', 'Required field target_mm is missing.');
    end
    target_mm = config.target_mm;
    if ~isnumeric(target_mm) || numel(target_mm) ~= 3 || ...
            ~isreal(target_mm) || any(~isfinite(target_mm), 'all')
        error('hermes:InvalidTarget', ...
            'target_mm must be a finite numeric [x,y,z] vector.');
    end
    targets_mm = double(target_mm(:).');
    if isfield(config, 'targets_mm')
        targets_mm = config.targets_mm;
        if ~isnumeric(targets_mm) || size(targets_mm, 2) ~= 3 || ...
                isempty(targets_mm) || size(targets_mm, 1) > 8 || ...
                ~isreal(targets_mm) || any(~isfinite(targets_mm), 'all')
            error('hermes:InvalidTargets', ...
                'targets_mm must contain one to eight finite [x,y,z] rows.');
        end
        if any(abs(double(targets_mm(1, :))-double(target_mm(:).')) > 1e-9)
            error('hermes:PrimaryTargetMismatch', ...
                'The first targets_mm row must equal target_mm.');
        end
    end
    options = struct();
    if isfield(config, 'frequency_hz'), options.frequency_hz = config.frequency_hz; end
    if isfield(config, 'modulation_frequency_hz')
        options.modulation_frequency_hz = config.modulation_frequency_hz;
    end
    if isfield(config, 'element_count'), options.element_count = config.element_count; end
    if isfield(config, 'polarization'), options.polarization = config.polarization; end
    if isfield(config, 'random_seed'), options.random_seed = config.random_seed; end

    interface_root = fileparts(mfilename('fullpath'));
    project_root = fileparts(interface_root);
    addpath(fullfile(project_root, 'matlab_core'), '-begin');
    core_result = run_focus_core(double(targets_mm), options);
    artifact_parent = string(fileparts(result_path));
    if strlength(artifact_parent) == 0, artifact_parent = string(pwd); end
    field_mat_path = fullfile(artifact_parent, 'field_data.mat');
    save(field_mat_path, 'core_result', '-v7.3');
    active_indices = core_result.user_harmonic_indices;
    orthogonal = core_result.orthogonal_planes;
    field_payload = struct( ...
        'schema_version', 2, ...
        'task_id', task_id, ...
        'x_mm', core_result.maps.x_lambda*core_result.wavelength_mm, ...
        'z_mm', core_result.maps.z_lambda*core_result.wavelength_mm, ...
        'harmonic_orders', core_result.harmonic_orders, ...
        'harmonic_frequencies_hz', core_result.harmonic_frequencies_hz, ...
        'user_harmonic_orders', core_result.user_harmonic_orders, ...
        'user_harmonic_indices', active_indices, ...
        'requested_focus_points_mm', core_result.requested_focus_points_mm, ...
        'actual_peak_points_mm', core_result.actual_peak_points_mm, ...
        'normalized_power_by_user', ...
            core_result.maps.local_power(:, :, active_indices), ...
        'raw_power_by_user', ...
            core_result.maps.raw_power_absolute(:, :, active_indices), ...
        'y_mm', orthogonal.y_lambda*core_result.wavelength_mm, ...
        'yz_z_mm', orthogonal.yz_z_lambda*core_result.wavelength_mm, ...
        'yz_plane_x_mm_by_user', orthogonal.yz_fixed_x_mm_by_user, ...
        'normalized_power_yz_by_user', ...
            orthogonal.yz_normalized_power_by_user, ...
        'xy_x_mm', orthogonal.xy_x_lambda*core_result.wavelength_mm, ...
        'xy_y_mm', orthogonal.xy_y_lambda*core_result.wavelength_mm, ...
        'xy_plane_z_mm_by_user', orthogonal.xy_fixed_z_mm_by_user, ...
        'normalized_power_xy_by_user', ...
            orthogonal.xy_normalized_power_by_user, ...
        'orthogonal_plane_resolution', orthogonal.resolution, ...
        'orthogonal_plane_normalization', orthogonal.normalization, ...
        'fwhm_x_mm_by_user', core_result.fwhm_x_mm_by_user, ...
        'dof_z_mm_by_user', core_result.dof_z_mm_by_user, ...
        'peak_to_sidelobe_ratio_db_by_user', ...
            core_result.peak_to_sidelobe_ratio_db_by_user, ...
        'peak_to_sidelobe_definition', ...
            core_result.peak_to_sidelobe_definition, ...
        'matlab_version', string(version), ...
        'matlab_release', string(version('-release')), ...
        'matlab_arch', string(computer('arch')), ...
        'random_seed', core_result.random_seed, ...
        'rng_algorithm', core_result.rng_algorithm);
    write_json_result(fullfile(artifact_parent, 'field_data.json'), field_payload);
    payload = struct('status', "success", 'task_id', task_id, ...
        'requested_focus_mm', core_result.requested_focus_mm, ...
        'actual_peak_mm', core_result.actual_peak_mm, ...
        'peak_power', core_result.peak_power, ...
        'peak_power_definition', core_result.peak_power_definition, ...
        'requested_power', core_result.requested_power, ...
        'requested_focus_points_mm', core_result.requested_focus_points_mm, ...
        'actual_peak_points_mm', core_result.actual_peak_points_mm, ...
        'peak_power_by_user', core_result.peak_power_by_user, ...
        'requested_power_by_user', core_result.requested_power_by_user, ...
        'focus_error_mm_by_user', core_result.focus_error_mm_by_user, ...
        'fwhm_x_mm_by_user', core_result.fwhm_x_mm_by_user, ...
        'dof_z_mm_by_user', core_result.dof_z_mm_by_user, ...
        'peak_to_sidelobe_ratio_db_by_user', ...
            core_result.peak_to_sidelobe_ratio_db_by_user, ...
        'peak_to_sidelobe_definition', ...
            core_result.peak_to_sidelobe_definition, ...
        'user_count', core_result.user_count, ...
        'frequency_hz', core_result.frequency_hz, ...
        'modulation_frequency_hz', core_result.modulation_frequency_hz, ...
        'harmonic_orders', core_result.harmonic_orders, ...
        'harmonic_frequencies_hz', core_result.harmonic_frequencies_hz, ...
        'user_harmonic_orders', core_result.user_harmonic_orders, ...
        'user_harmonic_indices', core_result.user_harmonic_indices, ...
        'orthogonal_plane_resolution', orthogonal.resolution, ...
        'wavelength_mm', core_result.wavelength_mm, ...
        'element_count', core_result.element_count, ...
        'element_positions_mm', core_result.element_positions_mm, ...
        'polarization', core_result.polarization, ...
        'polarization_model', core_result.polarization_model, ...
        'method', core_result.method, ...
        'hardware_realization', core_result.hardware_realization, ...
        'array_geometry', core_result.array_geometry, ...
        'matlab_version', string(version), ...
        'matlab_release', string(version('-release')), ...
        'matlab_arch', string(computer('arch')), ...
        'random_seed', core_result.random_seed, ...
        'rng_algorithm', core_result.rng_algorithm, ...
        'artifacts', struct('field_json', "field_data.json", ...
            'field_mat', "field_data.mat"), ...
        'runtime_sec', toc(started));
catch exception
    error_type = string(exception.identifier);
    if strlength(error_type) == 0
        error_type = string(class(exception));
    end
    payload = struct('status', "error", 'task_id', task_id, ...
        'error_type', error_type, 'message', string(exception.message), ...
        'runtime_sec', toc(started));
end

write_json_result(result_path, payload);
end

function write_json_result(result_path, payload)
result_path = string(result_path);
parent = string(fileparts(result_path));
if strlength(parent) == 0
    parent = string(pwd);
end
if ~isfolder(parent)
    mkdir(parent);
end
encoded = jsonencode(payload, 'PrettyPrint', true);
temporary_path = string(tempname(char(parent)))+".json.tmp";
[file_id, message] = fopen(temporary_path, 'w', 'n', 'UTF-8');
assert(file_id >= 0, 'hermes:ResultWriteError', ...
    'Could not open temporary result JSON: %s', message);
bytes_written = fprintf(file_id, '%s\n', encoded);
close_status = fclose(file_id);
if bytes_written <= 0 || close_status ~= 0
    if isfile(temporary_path), delete(temporary_path); end
    error('hermes:ResultWriteError', ...
        'Could not finish writing result JSON: %s', result_path);
end
[moved, move_message] = movefile(temporary_path, result_path, 'f');
if ~moved
    if isfile(temporary_path), delete(temporary_path); end
    error('hermes:ResultWriteError', ...
        'Could not publish result JSON: %s', move_message);
end
end
