function report = test_consistency(baseline_path)
%TEST_CONSISTENCY Compare extracted core with source-project baseline data.

project_root = string(fileparts(fileparts(mfilename('fullpath'))));
if nargin < 1
    baseline_path = fullfile(project_root, 'runs', 'original_baseline.mat');
end
assert(isfile(baseline_path), ...
    'Baseline missing. Run generate_original_baseline first: %s', baseline_path);
baseline = load(baseline_path);
restoredefaultpath;
addpath(fullfile(project_root, 'matlab_core'), '-begin');

template = struct('target_mm', [], 'original_actual_peak_mm', [], ...
    'new_actual_peak_mm', [], 'actual_peak_difference_mm', NaN, ...
    'original_peak_power', NaN, 'new_peak_power', NaN, ...
    'peak_power_absolute_difference', NaN, ...
    'peak_power_relative_difference', NaN, ...
    'excitation_max_absolute_difference', NaN, ...
    'field_power_map_max_absolute_difference', NaN, 'passed', false);
cases = repmat(template, numel(baseline.cases), 1);
for index = 1:numel(baseline.cases)
    original = baseline.cases(index);
    fresh = run_focus_core(original.target_mm);
    peak_difference = norm(fresh.actual_peak_mm-original.actual_peak_mm);
    power_difference = abs(fresh.peak_power-original.peak_power);
    relative_power_difference = power_difference/max(abs(original.peak_power), eps);
    excitation_difference = max(abs( ...
        fresh.excitation.harmonic_weights-original.harmonic_weights), [], 'all');
    map_difference = max(abs( ...
        fresh.maps.raw_power_absolute(:, :, 1)-original.raw_power_map), [], 'all');
    passed = peak_difference <= 1e-10 && ...
        relative_power_difference <= 1e-12 && ...
        excitation_difference <= 1e-12 && map_difference <= 1e-9;
    cases(index) = struct('target_mm', original.target_mm, ...
        'original_actual_peak_mm', original.actual_peak_mm, ...
        'new_actual_peak_mm', fresh.actual_peak_mm, ...
        'actual_peak_difference_mm', peak_difference, ...
        'original_peak_power', original.peak_power, ...
        'new_peak_power', fresh.peak_power, ...
        'peak_power_absolute_difference', power_difference, ...
        'peak_power_relative_difference', relative_power_difference, ...
        'excitation_max_absolute_difference', excitation_difference, ...
        'field_power_map_max_absolute_difference', map_difference, ...
        'passed', passed);
end
report = struct('passed', all([cases.passed]), 'cases', cases, ...
    'baseline_source_root', baseline.source_root, ...
    'baseline_generated_at', baseline.generated_at);
assert(report.passed, 'Source/extracted consistency comparison failed.');
json_path = fullfile(project_root, 'runs', 'consistency_report.json');
write_report(json_path, report);
fprintf('TEST_CONSISTENCY_PASS %s\n', json_path);
end

function write_report(path, report)
[file_id, message] = fopen(path, 'w', 'n', 'UTF-8');
assert(file_id >= 0, 'Could not write consistency report: %s', message);
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, '%s\n', jsonencode(report, 'PrettyPrint', true));
end
