function report = test_orthogonal_field_planes()
%TEST_ORTHOGONAL_FIELD_PLANES Verify true MATLAB XOZ/YOZ/XOY field evidence.

project_root = string(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(project_root, 'matlab_core'), '-begin');
options = struct('frequency_hz', 28e9, ...
    'modulation_frequency_hz', 200e6, 'element_count', 16);
result = run_focus_core([10, 0, 100], options);
planes = result.orthogonal_planes;

assert(planes.resolution == 101, ...
    'Orthogonal visualization planes must use the bounded 101-point grid.');
assert(isequal([size(planes.yz_normalized_power_by_user, 1), ...
    size(planes.yz_normalized_power_by_user, 2)], [101, 101]), ...
    'The focal YZ field cut has an unexpected shape.');
assert(isequal([size(planes.xy_normalized_power_by_user, 1), ...
    size(planes.xy_normalized_power_by_user, 2)], [101, 101]), ...
    'The focal XY field cut has an unexpected shape.');
assert(size(planes.yz_normalized_power_by_user, 3) == 1 && ...
    size(planes.xy_normalized_power_by_user, 3) == 1, ...
    'Every user must have one YZ and one XY field cut.');
assert(abs(planes.yz_fixed_x_mm_by_user) < 1e-12, ...
    'The strict YOZ cut must use X=0.');
assert(abs(planes.xy_fixed_z_mm_by_user-result.actual_peak_mm(3)) < 1e-9, ...
    'The XY cut must pass through the measured focal Z coordinate.');
assert(abs(max(planes.yz_normalized_power_by_user, [], 'all')-1) < 1e-12, ...
    'The YZ field cut must be normalized.');
assert(abs(max(planes.xy_normalized_power_by_user, [], 'all')-1) < 1e-12, ...
    'The XY field cut must be normalized.');
assert(all(isfinite(planes.yz_normalized_power_by_user), 'all') && ...
    all(isfinite(planes.xy_normalized_power_by_user), 'all'), ...
    'Orthogonal field cuts must contain finite values.');

report = struct('passed', true, 'actual_peak_mm', result.actual_peak_mm, ...
    'orthogonal_resolution', planes.resolution);
fprintf('TEST_ORTHOGONAL_FIELD_PLANES_PASS\n');
end
