function report = test_metasurface_core()
%TEST_METASURFACE_CORE Minimal real-MATLAB binary transmitarray verification.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'matlab_core', 'metasurface_design'), '-begin');

candidateTemplate = struct( ...
    'candidate_id', "", 'mode', "", 'optimizer', "", ...
    'max_iterations', 0, 'guard_weight', 0, 'seed', 0);
candidates = repmat(candidateTemplate, 4, 1);
candidates(1).candidate_id = "reference_unprogrammed";
candidates(1).mode = "unprogrammed";
candidates(2).candidate_id = "reference_continuous";
candidates(2).mode = "continuous_phase_conjugate";
candidates(3).candidate_id = "baseline_geometrical_optics";
candidates(3).mode = "geometrical_optics_binary";
candidates(4).candidate_id = "optimized_binary";
candidates(4).mode = "optimized_binary";
candidates(4).optimizer = "binary_coordinate_descent_v1";
candidates(4).max_iterations = 1;
candidates(4).guard_weight = 0.25;
candidates(4).seed = 7;

config = struct( ...
    'focus_target_mm', [20, 0, 100], ...
    'focus_tolerance_mm', 8, ...
    'frequency_hz', 28e9, ...
    'surface_geometry', "planar", ...
    'unit_size_mm', [5, 5, 1], ...
    'array_size', [8, 8], ...
    'incident_wave', "plane_wave", ...
    'horn_feed_position_mm', [0, 0, -100], ...
    'binary_states', struct( ...
        'state_0', struct('amplitude', 1, 'phase_deg', 0), ...
        'state_1', struct('amplitude', 1, 'phase_deg', 180)), ...
    'roi_radius_mm', 15, ...
    'roi_half_depth_mm', 20, ...
    'candidates', candidates);
results = design_planar_metasurface_batch_core(config);

assert(numel(results) == 4);
assert(all(string({results.status}) == "success"));
assert(isempty(results(2).phase_codes));
assert(numel(results(3).phase_codes) == prod(config.array_size));
assert(numel(results(4).phase_codes) == prod(config.array_size));
assert(all(ismember(results(4).phase_codes, [0, 1])));
assert(size(results(4).normalized_power_xz, 1) == 201);
assert(size(results(4).normalized_power_xz, 2) == 201);
assert(all(isfinite(results(4).normalized_power_xz), 'all'));
assert(abs(results(4).input_power_proxy-prod(config.array_size)) < 1e-9);
assert(abs(results(4).transmission_efficiency_proxy-1) < 1e-9);
assert(results(2).target_power >= results(3).target_power);
assert(results(3).target_power > results(1).target_power);
assert(results(4).focus_error_mm <= results(3).focus_error_mm+1e-9);

dryRunDir = tempname;
mkdir(dryRunDir);
cleanup = onCleanup(@()rmdir(dryRunDir, 's')); %#ok<NASGU>
cstConfig = struct( ...
    'launch_cst', false, 'model_kind', "layout_scaffold", ...
    'cst_prog_id', "CSTStudio.Application.2025", ...
    'output_cst_path', fullfile(dryRunDir, 'layout.cst'), ...
    'output_vba_path', fullfile(dryRunDir, 'layout.vba'), ...
    'frequency_ghz', 28, 'focus_target_mm', config.focus_target_mm, ...
    'unit_size_mm', config.unit_size_mm, 'array_size', config.array_size, ...
    'element_positions_mm', results(4).element_positions_mm, ...
    'phase_codes', results(4).phase_codes);
cst = build_cst_layout_model_core(cstConfig);
assert(~cst.cst_launched);
assert(~cst.cst_launch_requested);
assert(cst.launch_retry_supported);
assert(strlength(cst.launch_error_message) == 0);
assert(isfile(cst.vba_history_path));
vba = fileread(cst.vba_history_path);
assert(contains(vba, 'LAYOUT ONLY'));
assert(contains(vba, 'binary_state_0'));
assert(contains(vba, 'binary_state_1'));

report = struct( ...
    'passed', true, ...
    'unprogrammed_focus_error_mm', results(1).focus_error_mm, ...
    'go_focus_error_mm', results(3).focus_error_mm, ...
    'optimized_focus_error_mm', results(4).focus_error_mm, ...
    'go_target_power', results(3).target_power, ...
    'optimized_target_power', results(4).target_power, ...
    'optimized_pslr_db', results(4).peak_to_sidelobe_ratio_db, ...
    'cst_layout_cell_count', cst.cell_count);
disp(jsonencode(report, 'PrettyPrint', true));
end
