function report = test_multiuser_harmonics()
%TEST_MULTIUSER_HARMONICS Verify one distinct harmonic channel per user.

project_root = string(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(project_root, 'matlab_core'), '-begin');
options = struct('frequency_hz', 28e9, ...
    'modulation_frequency_hz', 200e6, 'element_count', 64);
result = run_focus_core([0, 0, 100; 20, 0, 90], options);

assert(isequal(result.user_harmonic_orders, [-1, 1]), ...
    'Two users must map to q=-1 and q=+1.');
assert(isequal(result.harmonic_orders, [-1, 0, 1]), ...
    'The frequency plan must retain the inactive q=0 carrier channel.');
assert(max(abs(result.excitation.harmonic_weights(:, 2)), [], 'all') == 0, ...
    'The inactive q=0 channel must not contain a hidden multi-focus excitation.');
assert(all(abs(result.harmonic_frequencies_hz-[27.8e9, 28e9, 28.2e9]) < 1), ...
    'The harmonic frequencies do not match fc+q*fm.');
assert(size(result.actual_peak_points_mm, 1) == 2, ...
    'MATLAB must return one measured local peak per harmonic user.');

report = struct('passed', true, ...
    'user_harmonic_orders', result.user_harmonic_orders, ...
    'harmonic_frequencies_hz', result.harmonic_frequencies_hz, ...
    'actual_peak_points_mm', result.actual_peak_points_mm);
fprintf('TEST_MULTIUSER_HARMONICS_PASS\n');
end
